In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits,on='title')
movies.shape

(4809, 23)

In [6]:
movies = movies[['id','title','genres','keywords','overview','cast','crew']]

In [7]:
movies.head()

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [9]:
movies.isna().sum()

id          0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [12]:
def convert(obj):
    l = []
    obj = ast.literal_eval(obj)
    for i in obj:
        l.append(i['name'])
    return l

In [13]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [14]:
movies['genres'] = movies['genres'].apply(convert)

In [15]:
movies['keywords'] = movies['keywords'].apply(convert)

In [16]:
def convert3(obj):
    l = []
    c = 1
    obj = ast.literal_eval(obj)
    for i in obj:
        if c<=3:
            l.append(i['name'])
            c+=1
    return l

In [17]:
movies['cast'] = movies['cast'].apply(convert3)

In [18]:
def convert2(obj):
    l = []
    obj = ast.literal_eval(obj)
    for i in obj:
        if i['job']=='Director':
            l.append(i['name'])
    return l

In [19]:
convert2(movies['crew'][0])

['James Cameron']

In [20]:
movies['crew'] = movies['crew'].apply(convert2)

In [21]:
movies.head(1)

,id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [22]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [23]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [24]:
df = movies[['id','title','tags']]

In [25]:
df['tags'] = df['tags'].apply(lambda x:' '.join(x))

C:\Users\Aavej\AppData\Local\Temp\ipykernel_15960\3089831005.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:' '.join(x))

In [26]:
df['tags'] = df['tags'].apply(lambda x: x.lower())

C:\Users\Aavej\AppData\Local\Temp\ipykernel_15960\4276611149.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x: x.lower())

In [27]:
import nltk

In [28]:
import re

In [29]:
steammer = nltk.stem.PorterStemmer()

In [30]:
stopwords=nltk.corpus.stopwords.words('english')

In [31]:
def processes(r1):
    r1 = r1.lower()
    r1 = re.sub('[^a-z]',' ',r1)
    words = [steammer.stem(i) for i in r1.split() if i not in stopwords]
    return ' '.join(words)

In [32]:
df['tags'] = df['tags'].apply(processes)

C:\Users\Aavej\AppData\Local\Temp\ipykernel_15960\619483850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(processes)

,id,title,tags
0,19995,Avatar,nd centuri parapleg marin dispatch moon pandor...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believ dead come back li...
2,206647,Spectre,cryptic messag bond past send trail uncov sini...
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...
4,49529,John Carter,john carter war weari former militari captain ...
...,...,...,...
4804,9367,El Mariachi,el mariachi want play guitar carri famili trad...
4805,72766,Newlyweds,newlyw coupl honeymoon upend arriv respect sis...
4806,231617,"Signed, Sealed, Delivered",sign seal deliv introduc dedic quartet civil s...
4807,126186,Shanghai Calling,ambiti new york attorney sam sent shanghai ass...
4808,25975,My Date with Drew,ever sinc second grade first saw e extraterres...

In [33]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [34]:
vectorizer =  CountVectorizer(max_features=5000)
bow = vectorizer.fit_transform(df['tags'])
x_train = bow.toarray()

In [35]:
x_train.shape

(4806, 5000)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
similarity = cosine_similarity(x_train)

In [38]:
df[df['title'] == 'Avatar'].id[0]

19995

In [39]:
def rec(movie):
    id = df[df['title'] == movie].index[0]
    return id

In [40]:
rec('Avatar')

0

In [41]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (2409, 0.4705982870544018),
 (4336, 0.41067708562283906),
 (1537, 0.3836484682442342),
 (838, 0.3785830732153027),
 (3162, 0.37447370529970864),
 (373, 0.3657028873603655),
 (2021, 0.3543178312491844),
 (1920, 0.35309393180189974),
 (2204, 0.33345191509920946),
 (300, 0.33207783609126584),
 (305, 0.3280101906601258),
 (1082, 0.31980107453341566),
 (278, 0.3165571568323276),
 (158, 0.315816813580689),
 (3538, 0.3064142895501718),
 (1715, 0.30403449605253013),
 (577, 0.3038948705590345),
 (461, 0.30244626571947736),
 (3736, 0.3018889419011508),
 (260, 0.3015113445777636),
 (507, 0.29965967090575757),
 (1321, 0.2954400247343626),
 (149, 0.29542903223069444),
 (4, 0.2934376852873043),
 (1355, 0.2857142857142857),
 (778, 0.2849014411490948),
 (184, 0.28401727598894266),
 (582, 0.2826397548966205),
 (1071, 0.2826397548966205),
 (47, 0.280305955290694),
 (2970, 0.27498714598438984),
 (1216, 0.27276395673749004),
 (1204, 0.27241788264159783),
 (239, 0.27214802830826107),
 (94, 0.2718118354334003),
 (661, 0.2709733813985673),
 (539, 0.26696477899043675),
 (972, 0.2636371929462334),
 (1357, 0.2625752465908215),
 (1220, 0.2584382953523688),
 (541, 0.25806238490561006),
 (973, 0.2543838652863964),
 (4048, 0.25367573584818975),
 (2971, 0.25017596686181365),
 (1344, 0.25010820169301234),
 (322, 0.25002164408471217),
 (502, 0.25002164408471217),
 (95, 0.2494690259492393),
 (2701, 0.2487554967702519),
 (595, 0.2480496629691867),
 (1957, 0.24694634187431175),
 (1056, 0.24604113061761196),
 (1765, 0.2451663926939418),
 (2938, 0.24420123527065274),
 (74, 0.2417468892076141),
 (56, 0.24174688920761406),
 (3212, 0.23878055736832968),
 (1201, 0.23805588025744623),
 (1965, 0.23762422826087876),
 (150, 0.23508271959274057),
 (230, 0.23508271959274055),
 (91, 0.23480533575620344),
 (432, 0.2332271006590722),
 (3675, 0.2332271006590722),
 (549, 0.22972292920210557),
 (83, 0.2279211529192759),
 (770, 0.22574301684783482),
 (52, 0.22254605016040768),
 (3147, 0.21989008243131009),
 (1278, 0.21950785944383266),
 (61, 0.21897956058054358),
 (754, 0.21886734967869412),
 (692, 0.21793430611327821),
 (1996, 0.21743634501273407),
 (3409, 0.21513017393089515),
 (1373, 0.2135718231923494),
 (581, 0.21164107056789905),
 (787, 0.21054454238712605),
 (1089, 0.20827698171247797),
 (236, 0.2077096468163805),
 (342, 0.2055165254597358),
 (3999, 0.20467923754178652),
 (1322, 0.20262210756744514),
 (1031, 0.2016308438129849),
 (1668, 0.20160491225300203),
 (41, 0.2014557410063451),
 (466, 0.20145574100634503),
 (773, 0.20073126386549828),
 (1982, 0.19947430219656304),
 (557, 0.1994310088043664),
 (27, 0.19913563590443212),
 (1479, 0.19738550848793066),
 (228, 0.19638608176993513),
 (270, 0.1948051948051948),
 (4192, 0.19382872151427658),
 (1329, 0.19149207069693872),
 (855, 0.18934485065929513),
 (454, 0.1893448506592951),
 (1656, 0.18877260556210576),
 (1488, 0.1873500336269922),
 (67, 0.1868706368604627),
 (1928, 0.1866498799767108),
 (168, 0.18609684207969418),
 (3608, 0.18609684207969418),
 (1285, 0.18571510456575832),
 (1496, 0.18541140018500424),
 (306, 0.18486846666163392),
 (889, 0.18486846666163392),
 (2547, 0.18422647458873526),
 (1178, 0.18235850450065405),
 (4353, 0.18233692233542073),
 (3188, 0.17965674766740417),
 (643, 0.17956508137863275),
 (3628, 0.17956508137863275),
 (46, 0.17803684012832613),
 (1297, 0.17803684012832613),
 (740, 0.17618776519129867),
 (1280, 0.17589669862367344),
 (3819, 0.17383837384127887),
 (480, 0.17367609220066726),
 (2787, 0.1733656789191194),
 (1002, 0.17305064017267058),
 (1831, 0.17229219690157918),
 (2865, 0.17221942300312604),
 (931, 0.17180203318601237),
 (4405, 0.1709408646894569),
 (579, 0.17058877190638633),
 (942, 0.1698823971458752),
 (111, 0.16903085094570333),
 (3218, 0.16861503026429298),
 (4343, 0.1684330388132427),
 (2786, 0.16802570317748738),
 (626, 0.16707000365517843),
 (3072, 0.16638161999547052),
 (141, 0.1662285851638025),
 (2916, 0.1646308945828745),
 (2450, 0.16460132459708002),
 (233, 0.1637433900334292),
 (4596, 0.1637433900334292),
 (229, 0.163731653417994),
 (3730, 0.16283473681973243),
 (87, 0.16280082351376848),
 (1383, 0.1622955862793958),
 (1361, 0.16164353767314799),
 (4468, 0.16116459280507606),
 (564, 0.16116459280507603),
 (2999, 0.16116459280507603),
 (1083, 0.16050272309770905),
 (2235, 0.16017886739426204),
 (1097, 0.15957672558078226),
 (2439, 0.15954480704349314),
 (14, 0.15920308451727833),
 (200, 0.15826048840199922),
 (223, 0.15803488531025348),
 (1560, 0.1579345138264476),
 (156, 0.15736382119470582),
 (680, 0.15669579263200217),
 (2820, 0.15669579263200217),
 (843, 0.1565368905041356),
 (1444, 0.15644655469368599),
 (3327, 0.15644655469368599),
 (1275, 0.1564094248593684),
 (2515, 0.1564094248593684),
 (222, 0.15616249353389688),
 (18, 0.1560469459830898),
 (2556, 0.15584415584415584),
 (3449, 0.15462182986741113),
 (108, 0.1543033499620919),
 (101, 0.15430334996209188),
 (1396, 0.15430334996209188),
 (2584, 0.15410282570588388),
 (36, 0.15385879890875245),
 (26, 0.15314750335058025),
 (1446, 0.15314750335058025),
 (2676, 0.15228622596829317),
 (4664, 0.15122313285973865),
 (2022, 0.14982983545287878),
 (2333, 0.14877095408944616),
 (1037, 0.14836403344027177),
 (4114, 0.14836403344027177),
 (4230, 0.14836403344027177),
 (2902, 0.14832912014800337),
 (617, 0.14814874939752934),
 (249, 0.14813363449166972),
 (401, 0.14803913136594804),
 (483, 0.14803913136594804),
 (2762, 0.14803913136594804),
 (35, 0.14789477332930714),
 (2789, 0.14789477332930714),
 (456, 0.1474642199460629),
 (3431, 0.1468728997817254),
 (1109, 0.14661427499966254),
 (1883, 0.14572412715649125),
 (3443, 0.14572412715649125),
 (1466, 0.14564381625088382),
 (1019, 0.14379392104440059),
 (2003, 0.14379392104440056),
 (642, 0.143576830751316),
 (2035, 0.143576830751316),
 (2731, 0.14238121546156626),
 (1379, 0.1419007662955948),
 (2059, 0.1413506985480439),
 (628, 0.14104963175564433),
 (3195, 0.14101901870444153),
 (800, 0.14067598969066597),
 (1774, 0.14067598969066597),
 (3093, 0.14067598969066597),
 (939, 0.1406165700513982),
 (127, 0.14030530132648028),
 (1529, 0.14030530132648025),
 (2284, 0.1402757726928108),
 (4325, 0.1402757726928108),
 (3728, 0.13957263155977065),
 (1570, 0.13957263155977062),
 (2347, 0.13957263155977062),
 (301, 0.13936662018318774),
 (232, 0.13903059987499417),
 (151, 0.13903059987499414),
 (2209, 0.13829796895557545),
 (755, 0.13759678177399753),
 (3235, 0.1374416265488099),
 (5, 0.13719241215239542),
 (587, 0.13719241215239542),
 (1294, 0.13719241215239542),
 (1467, 0.13719241215239542),
 (2135, 0.1367753011080483),
 (2763, 0.13596836013566976),
 (53, 0.1352463218994965),
 (279, 0.1352463218994965),
 (1658, 0.1348399724926484),
 (529, 0.13467381103397458),
 (3821, 0.13442056254198992),
 (473, 0.1335276300962446),
 (2075, 0.13298286813104201),
 (505, 0.13295400586957762),
 (365, 0.13287776639667082),
 (169, 0.13282595613759646),
 (31, 0.13241022442571243),
 (4545, 0.13213749452868195),
 (536, 0.1313204098072165),
 (110, 0.12987012987012986),
 (2058, 0.12940792666314374),
 (3755, 0.1292191476761844),
 (589, 0.12903494352312728),
 (220, 0.12893167424406085),
 (2169, 0.12893167424406085),
 (1741, 0.12861319288260692),
 (304, 0.12798102689389113),
 (1166, 0.12773807700531709),
 (1589, 0.1276613804646258),
 (3959, 0.1276613804646258),
 (1015, 0.12741179785940637),
 (490, 0.12697168670714545),
 (2732, 0.12662932291827406),
 (3291, 0.1264279082482028),
 (633, 0.12584840370807052),
 (70, 0.1252295124033085),
 (72, 0.1252295124033085),
 (1191, 0.12508798343090685),
 (1649, 0.12406456138646278),
 (1756, 0.12406456138646278),
 (2247, 0.12406456138646278),
 (207, 0.12347317093715587),
 (267, 0.12309149097933272),
 (1293, 0.12309149097933272),
 (1721, 0.12309149097933272),
 (1927, 0.12309149097933272),
 (208, 0.1228075425250719),
 (1445, 0.12217856249971876),
 (1161, 0.12182898077463454),
 (2239, 0.12182898077463454),
 (2888, 0.12182898077463453),
 (1418, 0.12172168970954686),
 (878, 0.1216517748906199),
 (3710, 0.1216517748906199),
 (1498, 0.12148238268746563),
 (1802, 0.12087344460380706),
 (1421, 0.12087344460380703),
 (2656, 0.12087344460380703),
 (2940, 0.12079796945151894),
 (2543, 0.12079796945151892),
 (900, 0.12075557676046032),
 (1018, 0.12075557676046032),
 (2488, 0.11971005425242182),
 (1439, 0.11869122675221742),
 (1700, 0.11869122675221742),
 (592, 0.11843130509275838),
 (107, 0.11692108443873354),
 (462, 0.11689566404829532),
 (870, 0.1168831168831169),
 (430, 0.11688311688311687),
 (3441, 0.11688311688311687),
 (4100, 0.11688311688311687),
 (419, 0.1167292531619702),
 (1793, 0.1167292531619702),
 (275, 0.11636000961466177),
 (1929, 0.11636000961466177),
 (1474, 0.11636000961466175),
 (3102, 0.11636000961466175),
 (790, 0.11613144917081455),
 (1299, 0.11613144917081455),
 (2760, 0.11539409918156433),
 (1617, 0.11486146460105282),
 (3572, 0.11486146460105279),
 (3630, 0.11486146460105279),
 (4316, 0.11486146460105279),
 (3556, 0.11467061807346574),
 (785, 0.11453468879067491),
 (487, 0.11396057645963795),
 (495, 0.11396057645963795),
 (1411, 0.11396057645963795),
 (2918, 0.11396057645963795),
 (3314, 0.11396057645963793),
 (363, 0.11326356333726345),
 (2133, 0.11326356333726345),
 (571, 0.11283778477771594),
 (3622, 0.11281521496355323),
 (256, 0.11241002017619531),
 (624, 0.11241002017619531),
 (7, 0.11222061815424865),
 (1938, 0.11222061815424865),
 (3905, 0.11190706454294862),
 (185, 0.11170370790654759),
 (2620, 0.11092107999698035),
 (3615, 0.11068829678133038),
 (172, 0.11062441971717746),
 (568, 0.11062441971717746),
 (311, 0.11062441971717744),
 (1039, 0.11062441971717744),
 (1324, 0.11062441971717744),
 (2433, 0.11062441971717744),
 (48, 0.10975392972191633),
 (1194, 0.10975392972191633),
 (1897, 0.10975392972191633),
 (3117, 0.10965861582662817),
 (147, 0.10957582335289495),
 (215, 0.10933414441871905),
 (784, 0.10896715305663912),
 (2001, 0.10896715305663912),
 (599, 0.10879460005359623),
 (138, 0.10855649121315493),
 (813, 0.1081970575195972),
 (4178, 0.10816659234722938),
 (459, 0.10811249552346708),
 (3770, 0.10811249552346708),
 (2323, 0.107682623063487),
 (10, 0.10756508696544757),
 (1092, 0.10756508696544757),
 (1042, 0.10744306187005072),
 (3756, 0.10711297487839565),
 (2868, 0.1067859115961747),
 (174, 0.10670461283174702),
 (1101, 0.10670461283174702),
 (2873, 0.10670461283174702),
 (3464, 0.10670461283174702),
 (794, 0.10660035817780522),
 (3810, 0.10646182613983998),
 (768, 0.10635445160304999),
 (1202, 0.10598118338653909),
 (4473, 0.10580973892262123),
 (4568, 0.10580973892262122),
 (585, 0.10566112966540278),
 (1749, 0.10566112966540278),
 (4512, 0.10566112966540278),
 (389, 0.10550699226799948),
 (1233, 0.10527227119356301),
 (997, 0.10522897599486018),
 (1639, 0.10522897599486018),
 (3354, 0.10474629747086911),
 (3498, 0.1047462974708691),
 (2498, 0.10457739712320041),
 (2796, 0.10457739712320041),
 (4010, 0.10457739712320041),
 (166, 0.10427294990624561),
 (362, 0.10427294990624561),
 (1501, 0.10403129732205987),
 (3378, 0.10403129732205987),
 (4181, 0.10389610389610389),
 (371, 0.10385482340819024),
 (404, 0.10308121991160743),
 (4602, 0.10308121991160743),
 (2072, 0.10298573010888744),
 (2713, 0.10298573010888744),
 (102, 0.10257253260583497),
 (1858, 0.10257253260583497),
 (660, 0.10233961877089325),
 (2456, 0.10233961877089325),
 (1823, 0.10213809651672394),
 (2243, 0.10213809651672394),
 (1614, 0.10213809651672393),
 (2718, 0.10192943828752513),
 (3181, 0.10192943828752513),
 (422, 0.10192943828752511),
 (2880, 0.1019294382875251),
 (4276, 0.1019294382875251),
 (1574, 0.10155400629994436),
 (814, 0.10131105378372258),
 (246, 0.10129829018634484),
 (980, 0.10081542190649244),
 (1113, 0.10081542190649244),
 (3008, 0.10081542190649244),
 (2017, 0.10072787050317253),
 (3159, 0.10072787050317251),
 (3781, 0.10072787050317251),
 (1898, 0.1006787229664564),
 (3231, 0.1005727851602267),
 (1531, 0.1005037815259212),
 (16, 0.10050378152592118),
 (413, 0.10050378152592118),
 (329, 0.09973715109828152),
 (556, 0.09973715109828152),
 (1768, 0.09973715109828152),
 (2583, 0.0997371510982815),
 (206, 0.09947294626039876),
 (2480, 0.09947294626039876),
 (4348, 0.09947294626039876),
 (476, 0.09918995010726926),
 (1327, 0.09918995010726926),
 (1524, 0.09918995010726926),
 (1942, 0.09918995010726926),
 (2506, 0.09918995010726926),
 (3721, 0.09918995010726926),
 (412, 0.09894548898363074),
 (1808, 0.09894548898363073),
 (420, 0.09888608009866892),
 (998, 0.09869275424396537),
 (4640, 0.09869275424396537),
 (4731, 0.09869275424396537),
 (30, 0.09819304088496757),
 (1273, 0.09819304088496757),
 (812, 0.09808164772274994),
 (1678, 0.09774284999977502),
 (1158, 0.09772038812426302),
 (1363, 0.0976804941082611),
 (3537, 0.0976804941082611),
 (854, 0.09745750213218746),
 (2297, 0.0971859061499725),
 (4097, 0.0971859061499725),
 (4587, 0.0971859061499725),
 (1098, 0.09673824874398686),
 (4694, 0.09673824874398686),
 (687, 0.09669875568304565),
 (187, 0.09669875568304563),
 (330, 0.09669875568304563),
 (400, 0.09669875568304563),
 (898, 0.09669875568304563),
 (1824, 0.09669875568304563),
 (3716, 0.09631426606617743),
 (4018, 0.09631426606617743),
 (1171, 0.09631426606617742),
 (2634, 0.09631426606617742),
 (3376, 0.09631426606617742),
 (3663, 0.09631426606617742),
 (4256, 0.09631426606617742),
 (1512, 0.09603468850667679),
 (3910, 0.09603468850667679),
 (4538, 0.09603468850667679),
 (332, 0.09574603534846936),
 (438, 0.09574603534846936),
 (524, 0.09574603534846936),
 (4079, 0.09574603534846936),
 (1362, 0.09574603534846934),
 (448, 0.09534625892455924),
 (635, 0.09534625892455922),
 (3982, 0.0950496913043515),
 (1068, 0.09496714704969829),
 (2053, 0.09496714704969829),
 (775, 0.0948209311861521),
 (3518, 0.0948209311861521),
 (4453, 0.0948209311861521),
 (2444, 0.09482093118615209),
 (2990, 0.09482093118615209),
 (862, 0.09467242532964756),
 (9, 0.09401267913629438),
 (2901, 0.09401267913629438),
 (11, 0.09392213430248139),
 (39, 0.09392213430248139),
 (1034, 0.09392213430248139),
 (2181, 0.09392213430248139),
 (2528, 0.09392213430248138),
 (3935, 0.09392213430248138),
 (122, 0.09367501681349609),
 (3289, 0.09367501681349609),
 (2448, 0.09343531843023135),
 (17, 0.09336653622777864),
 (777, 0.09336653622777864),
 (1301, 0.09336653622777864),
 (897, 0.0930484210398471),
 (1103, 0.0930484210398471),
 (2178, 0.0930484210398471),
 (3022, 0.0930484210398471),
 (632, 0.09304842103984709),
 (793, 0.09304842103984709),
 (307, 0.09285755228287917),
 (1878, 0.09273353546322172),
 (1828, 0.0927335354632217),
 (935, 0.09243423333081696),
 (2120, 0.09243423333081696),
 (4490, 0.09243423333081696),
 (271, 0.09219864597038363),
 (334, 0.09219864597038363),
 (859, 0.09219864597038363),
 (1237, 0.09219864597038363),
 (2158, 0.09219864597038363),
 (2696, 0.09219864597038363),
 (3764, 0.09219864597038363),
 (586, 0.09209405303147203),
 (2291, 0.09173649445877258),
 (1414, 0.09150522248280038),
 (1677, 0.09150522248280035),
 (1086, 0.0913717355809759),
 (3037, 0.0913717355809759),
 (294, 0.09124148357522649),
 (1274, 0.09124148357522649),
 (2496, 0.09124148357522649),
 (3661, 0.09124148357522649),
 (1288, 0.09116846116771037),
 (1655, 0.09116846116771037),
 (1745, 0.09116846116771037),
 (4333, 0.09116846116771037),
 (531, 0.09090909090909091),
 (1022, 0.0909090909090909),
 (3390, 0.0909090909090909),
 (123, 0.09071600943608701),
 (988, 0.09056668257034524),
 (3309, 0.09056668257034524),
 (3332, 0.09056668257034524),
 (4341, 0.09056668257034524),
 (2904, 0.09032446046618908),
 (33, 0.09009374626955591),
 (4000, 0.09009374626955591),
 (4236, 0.09009374626955591),
 (535, 0.08978254068931638),
 (312, 0.08978254068931636),
 (3450, 0.08978254068931636),
 (1005, 0.08939803125353485),
 (217, 0.08918825850158446),
 (982, 0.08918825850158446),
 (1277, 0.08918825850158446),
 (2023, 0.08918825850158446),
 (2054, 0.08918825850158446),
 (908, 0.08901842006416306),
 (1884, 0.08898825966347892),
 (253, 0.08863600391305174),
 (469, 0.08863600391305174),
 (3174, 0.08863600391305174),
 (3881, 0.08863600391305174),
 (4154, 0.08863600391305174),
 (704, 0.08827348295047495),
 (1011, 0.08827348295047495),
 (1565, 0.08827348295047495),
 (1632, 0.08827348295047495),
 (4205, 0.08827348295047495),
 (2834, 0.08809388259564936),
 (1452, 0.08809388259564935),
 (4165, 0.08772689266130253),
 (532, 0.0876267820584973),
 (3414, 0.0875615884016348),
 (4600, 0.08756158840163479),
 (3418, 0.08754693987147766),
 (809, 0.08703882797784893),
 (320, 0.08689412492187135),
 (1114, 0.08689412492187135),
 (1978, 0.08689412492187135),
 (4650, 0.08689412492187135),
 (513, 0.08683804610033365),
 (634, 0.08683804610033365),
 (1195, 0.08683804610033365),
 (3134, 0.08683804610033365),
 (3553, 0.08683804610033363),
 (3909, 0.08683804610033363),
 (2642, 0.08652532008633532),
 (125, 0.0861460984507896),
 (752, 0.0861460984507896),
 (1782, 0.0861460984507896),
 (2674, 0.0861460984507896),
 (4368, 0.0861460984507896),
 (4654, 0.0861460984507896),
 (1064, 0.08614609845078959),
 (731, 0.0859010165930062),
 (1585, 0.0859010165930062),
 (2378, 0.0859010165930062),
 (2396, 0.0859010165930062),
 (71, 0.08590101659300618),
 (511, 0.08590101659300618),
 (1306, 0.08590101659300618),
 (3377, 0.08576407395888476),
 (1701, 0.08547043234472847),
 (1623, 0.08547043234472845),
 (3066, 0.08547043234472845),
 (4789, 0.08503766788122594),
 (3201, 0.08501502839876024),
 (131, 0.0849411985729376),
 (449, 0.0849411985729376),
 (1843, 0.0849411985729376),
 (4339, 0.08494119857293758),
 (79, 0.08481041912882635),
 (192, 0.08481041912882634),
 (2644, 0.08481041912882634),
 (3954, 0.08464779113809698),
 (4026, 0.08464779113809698),
 (1497, 0.08455857861606325),
 (1516, 0.08455857861606325),
 (2598, 0.08428527216546852),
 (1783, 0.08416546361568648),
 (610, 0.08408749651825217),
 (1004, 0.08401285158874369),
 (2538, 0.08401285158874369),
 (4006, 0.08401285158874369),
 (4216, 0.08401285158874369),
 (4657, 0.08401285158874369),
 (4673, 0.08401285158874369),
 (103, 0.08353500182758924),
 (2264, 0.08353500182758924),
 (3400, 0.08353500182758924),
 (823, 0.08353500182758923),
 (1020, 0.08353500182758923),
 (2740, 0.08353500182758922),
 (319, 0.0832250378576479),
 (1240, 0.0832250378576479),
 (1575, 0.0832250378576479),
 (1673, 0.0832250378576479),
 (1747, 0.0832250378576479),
 (2161, 0.0832250378576479),
 (4206, 0.0832250378576479),
 (4611, 0.0832250378576479),
 (360, 0.08316847989130756),
 (1743, 0.08316847989130756),
 (3607, 0.08316847989130756),
 (744, 0.08311429258190126),
 (764, 0.08311429258190126),
 (941, 0.08311429258190126),
 (1833, 0.08311429258190126),
 (2553, 0.08311429258190126),
 (3926, 0.08311429258190126),
 (4626, 0.08311429258190126),
 (43, 0.08291849892341731),
 (170, 0.08291849892341731),
 (3206, 0.08291849892341731),
 (3634, 0.08291849892341731),
 (4279, 0.08291849892341731),
 (4777, 0.08291849892341731),
 (728, 0.08231544729143725),
 (1366, 0.08231544729143725),
 (3344, 0.08227895185745919),
 (627, 0.08224396186997114),
 (853, 0.08224396186997114),
 (1312, 0.08224396186997114),
 (1473, 0.08224396186997114),
 (1519, 0.08224396186997114),
 (3542, 0.08224396186997114),
 (808, 0.0818716950167146),
 (1262, 0.0818716950167146),
 (1675, 0.0818716950167146),
 (2114, 0.0818716950167146),
 (2270, 0.0818716950167146),
 (3709, 0.0818716950167146),
 (2758, 0.08184475910711347),
 (4045, 0.08172536479247935),
 (2968, 0.08172536479247934),
 (666, 0.08140041175688426),
 (75, 0.08140041175688424),
 (129, 0.08114779313969792),
 (297, 0.08114779313969792),
 (1340, 0.08114779313969792),
 (2898, 0.08114779313969792),
 (4087, 0.08114779313969792),
 (1832, 0.0811477931396979),
 (63, 0.08058229640253804),
 (341, 0.08058229640253803),
 (1096, 0.08058229640253803),
 (1465, 0.08058229640253803),
 (2012, 0.08058229640253803),
 (2579, 0.08058229640253801),
 (3769, 0.08058229640253801),
 (4680, 0.08058229640253801),
 (677, 0.08002845962381026),
 (274, 0.07984636960487998),
 (510, 0.07978836279039113),
 (2093, 0.07978836279039113),
 (2817, 0.07978836279039113),

In [42]:
def rec(movie):
    id = df[df['title'] == movie].index[0]
    distances = similarity[id]
    mov_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in mov_list:
        print(df.iloc[i[0]].title)

In [86]:
rec('The Amazing Spider-Man 2')

The Amazing Spider-Man
Spider-Man 3
Spider-Man
Spider-Man 2
Pan

In [85]:
df.sample(5)

,id,title,tags
2812,11658,Tae Guk Gi: The Brotherhood of War,south korea shoe shiner jin tae lee year old o...
4236,129139,The To Do List,feel pressur becom sexual experienc goe colleg...
1791,2055,Open Range,former gunsling forc take arm cattl crew threa...
3686,8435,A Cock and Bull Story,steve coogan arrog actor low self esteem compl...
38,102382,The Amazing Spider-Man 2,peter parker life busi take bad guy spider man...